[package]
name = "casper-sdk-rs"
version = "0.1.0"
authors = ["Mark A. Greenslade <asladeofgreen@pm.me>"]
description = "Pure rust SDK for casper-node."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/casper-network/casper-sdk-rs"
