[package]
name = "node-sse"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
eventsource-client = "0.13.0"
futures = "0.3.31"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
